version: 1.0.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: 1.0.0
  assembly_file_version: '{version}'
  assembly_informational_version: 1.0
environment:
  ASPNETCORE_ENVIRONMENT: Staging
  VersionSuffix: beta2
services: mssql2016
nuget:
  project_feed: true
  disable_publish_on_pr: true
build_script:
- ps: >-
    cd build

    .\build.ps1 -target CalculateCoverage
artifacts:
- path: build\artifacts\*.nupkg
deploy: off