version: $(ShortVersion).{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
environment:
  ASPNETCORE_ENVIRONMENT: Staging
  VersionSuffix: rc1
  ShortVersion: 1.0.0
services: mssql2016
nuget:
  project_feed: true
  disable_publish_on_pr: true
build_script:
- ps: >-
    cd build

    .\build.ps1 -target CalculateCoverage --settings_skipverification=true
artifacts:
- path: build\artifacts\*.nupkg
deploy: off