version: 1.0.0.{build}
branches:
  only:
  - master
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: 1.0.0
  assembly_file_version: '{version}'
  assembly_informational_version: 1.0
environment:
  Appveyor: true
services: mssql2014
nuget:
  project_feed: true
build_script:
- cmd: >-
    call build\BuildSolution.bat %CONFIGURATION%

    call build\CreatePackages.bat %CONFIGURATION% alpha-build%APPVEYOR_BUILD_NUMBER%
test_script:
- cmd: call build\RunTests.bat %CONFIGURATION%
artifacts:
- path: src\Infrastructure\**\*.nupkg
deploy: off