version: 1.0.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: 1.0.0
  assembly_file_version: '{version}'
  assembly_informational_version: 1.0
environment:
  ASPNETCORE_ENVIRONMENT: Staging
services: mssql2016
nuget:
  project_feed: true
  disable_publish_on_pr: true
build_script:
- cmd: >-
    call build\BuildSolution.bat %CONFIGURATION%

    call build\CreatePackages.bat %CONFIGURATION% beta1-build%APPVEYOR_BUILD_NUMBER%
test_script:
- cmd: call build\CalculateCoverage.bat
artifacts:
- path: src\Infrastructure\**\*.nupkg
deploy: off